### ISSUE TITLE
[1.11.2] [1.0.1] Crash after core sample/drill enters inventory; server

### ISSUE THREAD

**Issue by Rosethorns** [Flaxbeard/ImmersivePetroleum#13]
Unknown if it is the sample or the drill as both were picked up at once.
However client crashes due to holding one of those items.
`java.lang.NullPointerException: Unexpected error
	at flaxbeard.immersivepetroleum.common.EventHandler.renderLast(EventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_862_EventHandler_renderLast_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:166)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1421)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1250)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1053)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

**Comment by zcorcoran** [comment]
I'm getting the same crash and it appears to be the core sample. Deleting it from the player's inventory via an NBT editor makes the crash stop occurring. For me, the server was fine and only the client would crash. Oddly enough, based on the NBT data, the core sample in question contained no oil whatsoever.

**Comment by Flaxbeard** [comment]
Try updating to 1.0.2, I believe this bug was fixed

**Comment by Flaxbeard** [comment]
Closing issue unless it persists in the current version of the mod.
