### ISSUE TITLE
Core Sample Crash With invalid Config 

### ISSUE THREAD

**Issue by Nerodon** [Flaxbeard/ImmersivePetroleum#143]
Getting a an issue on immersivepetroleum-1.12.2-1.1.9, which caused client to not being able to t log in. Or crashing during game play.

There seems to be corruption happening with core samples after a server restart if you change the reservoir settings such as names, any samples that exist may refer to invalid reservoirs and throw a null pointer error.
If you log in while looking at a corrupted sample that is placed on the ground or look at it after login:

```
java.lang.NullPointerException: Unexpected error
	at flaxbeard.immersivepetroleum.common.EventHandler.renderCoresampleInfo(EventHandler.java:421)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_229_EventHandler_renderCoresampleInfo_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:911)
	at net.minecraftforge.client.GuiIngameForge.renderHUDText(GuiIngameForge.java:741)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:173)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1420)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

If you look at a sample in your inventory:

```
java.lang.NullPointerException: Rendering screen
	at flaxbeard.immersivepetroleum.common.EventHandler.handleItemTooltip(EventHandler.java:342)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_229_EventHandler_handleItemTooltip_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:335)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.gui.GuiScreen.func_191927_a(GuiScreen.java:143)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:737)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:684)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
Restoring the reservoir configs back to the previous when the core samples were created fixes the issue. 

ImmersivePetroleum should gracefully detect invalid samples and delete them or change them to a new state "Core sample invalid" on the client without crashing.

**Comment by Nerodon** [comment]
```
ReservoirType res = null;
for (ReservoirType type : PumpjackHandler.reservoirList.keySet())
{
	if (resName.equals(type.name))
	{
		res = type;
	}
}

String s = I18n.format("chat.immersivepetroleum.info.coresample.noOil");
if (amnt > 0)
{
	int est = (amnt / 1000) * 1000;
	String test = new DecimalFormat("#,###.##").format(est);
	Fluid f = FluidRegistry.getFluid(res.fluid);
	String fluidName = f.getLocalizedName(new FluidStack(f, 1));


	s = I18n.format("chat.immersivepetroleum.info.coresample.oil", test, fluidName);
}
```

We define res as null, then look into the reservoir list.
If the matching one isn't found res stays null.

Then if amnt > 0 we access res at line 421, which is null.

Crash.

The same code is used on both functions where I could get the crash
handleItemTooltip()
renderCoresampleInfo()

**Comment by ZeekDaGeek** [comment]
I'm getting the same issue, is there a way to get a client side patch that works in existing mod packs?

**Comment by ZeekDaGeek** [comment]
Actually additional information. It seems like this would be related as well:

```[22:45:43] [Server thread/ERROR] [FML]: A TileEntity type flaxbeard.immersivepetroleum.common.blocks.metal.TileEntityPumpjack has throw an exception trying to write state. It will not persist. Report this to the mod author
java.lang.ArithmeticException: / by zero
        at flaxbeard.immersivepetroleum.api.crafting.PumpjackHandler.getOilWorldInfo(PumpjackHandler.java:141) ~[PumpjackHandler.class:?]
        at flaxbeard.immersivepetroleum.api.crafting.PumpjackHandler.getFluid(PumpjackHandler.java:70) ~[PumpjackHandler.class:?]
        at flaxbeard.immersivepetroleum.common.blocks.metal.TileEntityPumpjack.availableFluid(TileEntityPumpjack.java:88) ~[TileEntityPumpjack.class:?]
        at flaxbeard.immersivepetroleum.common.blocks.metal.TileEntityPumpjack.writeCustomNBT(TileEntityPumpjack.java:147) ~[TileEntityPumpjack.class:?]
        at blusunrize.immersiveengineering.common.blocks.TileEntityIEBase.func_189515_b(TileEntityIEBase.java:48) ~[TileEntityIEBase.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:382) [aye.class:?]
        at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:173) [aye.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:202) [on.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73156_b(ChunkProviderServer.java:271) [on.class:?]
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:207) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by Flaxbeard** [comment]
I believe I've solved both crashes, will be in next build.
