### ISSUE TITLE
Error in server log upon start

### ISSUE THREAD

**Issue by TheK0tYaRa** [Flaxbeard/ImmersivePetroleum#155]
```
[04:42:31] [Server thread/ERROR] [FML]: Error registering event handler: FMLMod:immersivepetroleum{1.1.9} class blusunrize.immersiveengineering.api.MultiblockHandler$MultiblockFormEvent public void flaxbeard.immersivepetroleum.common.items.ItemProjector.handleMultiblockComplete(blusunrize.immersiveengineering.api.MultiblockHandler$MultiblockFormEvent)
java.lang.InstantiationException: null
        at sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_231]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_231]
        at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:130) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:112) [EventBus.class:?]
        at flaxbeard.immersivepetroleum.common.items.ItemProjector.<init>(ItemProjector.java:73) [ItemProjector.class:?]
        at flaxbeard.immersivepetroleum.common.IPContent.preInit(IPContent.java:146) [IPContent.class:?]
        at flaxbeard.immersivepetroleum.ImmersivePetroleum.preInit(ImmersivePetroleum.java:55) [ImmersivePetroleum.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
        at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231]
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?]
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?]
        at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?]
        at net.minecraftforge.fml.common.LoadController.redirect$forgeImpl$PostEvent$zza000(LoadController.java:568) [LoadController.class:?]
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
```

**Comment by Brycey92** [comment]
I'm getting the same error.

**Comment by bookerthegeek** [comment]
Tis the same error for me.

Minecraft 1.12.2
Immersive Engineering 0.12-92
immersive petroleum 1.12.2-1.1.9

**Comment by Khris777** [comment]
Same here, same versions.

**Comment by Flaxbeard** [comment]
Should be fixed for next release

**Comment by bookerthegeek** [comment]
> Should be fixed for next release

This will be for 1.12.2 ?

**Comment by Flaxbeard** [comment]
Yes, should be out later today

**Comment by Brycey92** [comment]
Is this still being released on CurseForge, or are releases being posted somewhere else? There hasn't been an update on CF since over 2 years ago.

**Comment by bookerthegeek** [comment]
@Brycey92 you always have to have proof you know. Pics or gtfo am I right? ;)
Proof : [HERE](https://i.imgur.com/2Pqtmcm.png)

**Comment by bookerthegeek** [comment]
> @Flaxbeard 
>> [Yes, should be out later today](https://github.com/Flaxbeard/ImmersivePetroleum/issues/155#issuecomment-624950993)

Just curious, which day were you referring to?
