### ISSUE TITLE
Divide by Zero Crash

### ISSUE THREAD

**Issue by herb26** [Flaxbeard/ImmersivePetroleum#163]
Upon activation of the Pumpjack multiblock in a chunk that contains a drained reservoir, the game crashes and the following crash message is given:
 java.lang.ArithmeticException: / by zero
	at flaxbeard.immersivepetroleum.api.crafting.PumpjackHandler.getOilWorldInfo(PumpjackHandler.java:141)
	at flaxbeard.immersivepetroleum.api.crafting.PumpjackHandler.getFluid(PumpjackHandler.java:70)
	at flaxbeard.immersivepetroleum.common.blocks.metal.TileEntityPumpjack.availableFluid(TileEntityPumpjack.java:88)
	at flaxbeard.immersivepetroleum.common.blocks.metal.TileEntityPumpjack.writeCustomNBT(TileEntityPumpjack.java:147)
	at blusunrize.immersiveengineering.common.blocks.TileEntityIEBase.func_189518_D_(TileEntityIEBase.java:58)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187273_a(PlayerChunkMapEntry.java:288)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187280_d(PlayerChunkMapEntry.java:273)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:115)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

Playing Sevtech Ages modpack if it helps.

**Comment by kereis** [comment]
Hey, I'm sorry that you might still fight against this issue. I've recently run into it too while playing SevTech Ages.

According to Commit 3ccb11d54bda7d8ee3bb1b70b8cb1cd3f144a62d, the issue is already fixed, but no new release was built against current changes. This leaves the problem in version 1.1.9 unresolved. In this case, you need to build a new JAR file with Gradle. I built one as version 1.1.10 but didn't publish it though.

Either way @Flaxbeard needs to build a new version with fix or maybe I can leave a download link for the fixed one.
