### ISSUE TITLE
Server crashed upon closing Immersive Engineering book

### ISSUE THREAD

**Issue by GameBurrow** [Flaxbeard/ImmersivePetroleum#176]
Server crashed upon closing Immersive Engineering book

**Version:** 1.14.4-2.0.0
**Forge version:** 1.14.4-28.2.23

**Crash log**
As file:
[crash-2020-09-29_19.01.59-server.txt](https://github.com/Flaxbeard/ImmersivePetroleum/files/5301319/crash-2020-09-29_19.01.59-server.txt)

```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 9/29/20 7:01 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.network.PacketBuffer.func_218666_n()Ljava/lang/String;
	at flaxbeard.immersivepetroleum.common.network.MessageCloseBook.<init>(MessageCloseBook.java:27) ~[?:2.0.0] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:116) ~[?:?] {re:classloading}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_212] {}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:116) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:157) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:79) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-1.0.0-service.jar:?] {}
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$0(NetworkHooks.java:74) ~[?:?] {re:classloading}
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_212] {}
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:74) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1275) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:701) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:695) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:681) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:628) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Linux (amd64) version 4.19.0-8-amd64
	Java Version: 1.8.0_212, IcedTea
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), IcedTea
	Memory: 10105632832 bytes (9637 MB) / 15032385536 bytes (14336 MB) up to 15032385536 bytes (14336 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:+UseG1GC -Xms1G -Xmx14G
	ModLauncher: 4.1.0+62+5bfa59b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.5-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.2.23.jar fml TRANSFORMATIONSERVICE 
	FML: 28.2
	Forge: net.minecraftforge:28.2.23
	FML Language Providers: 
		javafml@28.2
		minecraft@1
	Mod List: 
		forge-1.14.4-28.2.23-server.jar Minecraft {minecraft@1.14.4 DONE}
		industrial-foregoing-1.14.4-2.1.2-582ea8b.jar Industrial Foregoing {industrialforegoing@2.1.2 DONE}
		torchmaster-2.0.0-rc2.jar Torchmaster {torchmaster@2.0.0-rc2 DONE}
		inventorysorter-1.14.4-16.2.0.jar Simple Inventory Sorter {inventorysorter@16.2.0 DONE}
		Dynmap-3.0.1-forge-1.14.4.jar Dynmap {dynmap@3.0.1-343 DONE}
		MouseTweaks-2.13-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		titanium-1.14.4-2.2.10.jar Titanium {titanium@2.2.10 DONE}
		ImmersiveEngineering-1.14.4-4.0.0-116.jar Immersive Engineering {immersiveengineering@1.14.4-4.0.0-116 DONE}
		jei-1.14.4-6.0.1.30.jar Just Enough Items {jei@6.0.1.30 DONE}
		FallingTree-1.14.4-2.4.0.jar Falling Tree {falling_tree@2.4.0 DONE}
		astikorcarts-1.14.4-1.0.4.jar AstikorCarts {astikorcarts@1.0.4 DONE}
		TrackAPI-1.2.jar TrackAPI {trackapi@1.2 DONE}
		jeiintegration_1.14.4-2.0.0.jar JEI Integration {jeiintegration@2.0.0 DONE}
		gravestone-1.15.3.jar Gravestone Mod {gravestone@1.15.3 DONE}
		FTBUtilitiesBackups-2.0.0.11.jar FTB Utilities: Backups {ftbbackups@2.0.0.11 DONE}
		StorageDrawers-1.14.4-6.0.7.jar Storage Drawers {storagedrawers@1.14.4-6.0.6 DONE}
		performant-1.14.4-1.5.jar Performant {performant@1.5 DONE}
		harvest-1.14.4-1.0.1.jar Harvest {harvest@1.0.1 DONE}
		obfuscate-0.4.1-1.14.4.jar Obfuscate {obfuscate@0.4.1 DONE}
		Bookshelf-1.14.4-4.4.74.jar Bookshelf {bookshelf@4.4.74 DONE}
		buildinggadgets-3.2.0.jar Building Gadgets {buildinggadgets@3.2.0 DONE}
		furniture-7.0.0-pre15-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre15 DONE}
		Morpheus-1.14.4-4.2.44.jar Morpheus {morpheus@version DONE}
		ImmersiveRailroading-1.7.3_1.14.4.jar Immersive Railroading {immersiverailroading@1.7.3 DONE, universalmodcore@1.0 DONE}
		cc-tweaked-1.14.4-1.89.2.jar CC: Tweaked {computercraft@1.89.2 DONE}
		Hwyla-forge-1.10.6-B67_1.14.4.jar Waila {waila@version DONE}
		WAWLA-1.14.4-2.9.1.jar WAWLA {wawla@2.9.1 DONE}
		trashcans-1.0.3-mc1.14.jar Trash Cans {trashcans@1.0.3 DONE}
		mininggadgets-1.2.4.jar Mining Gadgets {mininggadgets@1.2.4 DONE}
		bwncr-1.14.4-3.5.12.jar Bad Wither No Cookie Reloaded {bwncr@1.14.4-3.5.12 DONE}
		ImmersivePetroleum-1.14.4-2.0.0.jar Immersive Petroleum {immersivepetroleum@2.0.0 DONE}
		forge-1.14.4-28.2.23-universal.jar Forge {forge@28.2.23 DONE}
		ServerTabInfo-1.14.4-1.2.6.jar Server Tab Info {servertabinfo@1.2.6 DONE}
		refinedstorage-1.7.3.jar Refined Storage {refinedstorage@1.7.3 DONE}
		refinedstorageaddons-0.5.jar Refined Storage Addons {refinedstorageaddons@0.5 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
	Player Count: 2 / 100; [ServerPlayerEntity['GameBurrow'/172, l='world', x=-17.54, y=71.00, z=-236.63], ServerPlayerEntity['Vulglorious'/2859, l='world', x=-8.63, y=64.00, z=-234.80]]
	Data Packs: vanilla, mod:astikorcarts, mod:bookshelf, mod:bwncr, mod:cfm, mod:computercraft, mod:forge, mod:gravestone, mod:harvest, mod:immersiveengineering, mod:immersiverailroading, mod:industrialforegoing (incompatible), mod:inventorysorter, mod:ironchest, mod:jei, mod:jeiintegration, mod:mousetweaks, mod:obfuscate, mod:refinedstorage, mod:refinedstorageaddons, mod:servertabinfo, mod:storagedrawers, mod:titanium (incompatible), mod:torchmaster, mod:trackapi (incompatible), mod:waila, mod:wawla, mod:falling_tree, mod:morpheus, mod:mininggadgets, mod:performant, mod:buildinggadgets, mod:dynmap, mod:ftbbackups, mod:immersivepetroleum, mod:trashcans (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by TwistedGate** [comment]
Have you tried with a lower forge version, like `28.2.16` (Which it was built against)

Higher versions of Forge tend to have changes that completely break stuff.

**Comment by GameBurrow** [comment]
Didn't, we moved our pack to 1.15, so atm I don't even have the mod.
