### ISSUE TITLE
Projector causing user to crash and disconnect from server

### ISSUE THREAD

**Issue by icebalm** [Flaxbeard/ImmersivePetroleum#228]
One of the players on my server created a projector and had it in his inventory for a few minutes, after a while he got disconnected and every time he tried logging back in it would kick him off with the same errors. Removing the projector from his inventory resolved the issue. Here's the log:

[19Feb2021 00:28:46.298] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer/]: Player joined the game
[19Feb2021 00:28:46.311] [Server thread/INFO] [Waila/]: Syncing config to Player ()
[19Feb2021 00:28:46.349] [Server thread/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/resources/I18n for invalid dist DEDICATED_SERVER
[19Feb2021 00:28:46.356] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class net/minecraft/client/resources/I18n for invalid dist DEDICATED_SERVER
        Index: 17
        Listeners:
                0: HIGHEST
                1: net.minecraftforge.eventbus.EventBus$$Lambda$2796/0x0000000800c06040@24542328
                2: ASM: wayoftime.bloodmagic.util.handler.event.GenericHandler@e2e79e2 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                3: NORMAL
                4: ASM: wayoftime.bloodmagic.util.handler.event.GenericHandler@e2e79e2 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                5: ASM: class com.simibubi.create.events.CommonEvents onUpdateLivingEntity(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                6: ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem holdingExtendoGripIncreasesRange(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                7: ASM: class cofh.ensorcellation.event.ShieldEnchEvents handleLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                8: ASM: class cofh.ensorcellation.event.HorseEnchEvents handleLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                9: ASM: class cofh.ensorcellation.event.CommonEvents handleLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                10: ASM: Block{naturesaura:animal_generator} onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                11: ASM: Block{null} onDragonTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                12: net.minecraftforge.eventbus.EventBus$$Lambda$2796/0x0000000800c06040@5610bdfa
                13: net.minecraftforge.eventbus.EventBus$$Lambda$2796/0x0000000800c06040@7449b18a
                14: ASM: de.ellpeck.naturesaura.items.ItemPetReviver$Events@49a80294 onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                15: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@5a1cdf23 tick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                16: ASM: mekanism.common.lib.radiation.RadiationManager@6d3be518 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                17: ASM: com.inventorypets.events.PlayerTickHandler@106046a4 onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                18: ASM: com.inventorypets.events.GravePetHandler@6bdf8c3d gravePetLoadEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                19: ASM: com.inventorypets.events.ItemEntityEvents@32d80ab7 handleLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                20: ASM: flaxbeard.immersivepetroleum.common.CommonEventHandler@7f101efd test(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                21: ASM: blusunrize.immersiveengineering.common.EventHandler@2d3aba1 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                22: ASM: squeek.appleskin.network.SyncHandler@70e16703 onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                23: ASM: shadows.apotheosis.ench.EnchModuleEvents@119fe59 lifeMend(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                24: ASM: vazkii.quark.content.tweaks.module.DragonScalesModule@64ecc3e onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                25: ASM: vazkii.quark.content.tweaks.module.PoisonPotatoUsageModule@120e6c21 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
                26: ASM: vazkii.quark.content.world.module.BiotiteModule@3d0614ae onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
java.lang.RuntimeException: Attempted to load class net/minecraft/client/resources/I18n for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71)
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at flaxbeard.immersivepetroleum.common.items.ProjectorItem.func_200295_i(ProjectorItem.java:99)
        at net.minecraft.item.ItemStack.func_200301_q(ItemStack.java:526)
        at com.inventorypets.events.PlayerTickHandler.onLivingUpdateEvent(PlayerTickHandler.java:153)
        at net.minecraftforge.eventbus.ASMEventHandler_677_PlayerTickHandler_onLivingUpdateEvent_LivingUpdateEvent.invoke(.dynamic)
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
        at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:331)
        at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112)
        at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223)
        at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404)
        at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:864)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641)
        at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by icebalm** [comment]
This is using Immersive Petroleum 3.1.0-2 on forge 1.16.5-36.0.15

**Comment by TwistedGate** [comment]
Please use [Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) for logs.
