### ISSUE TITLE
[BUG] `java.lang.NullPointerException` at `flaxbeard.immersivepetroleum.common.items.ItemProjector.func_77624_a(ItemProjector.java:92)`

### ISSUE THREAD

**Issue by zyxkad** [Flaxbeard/ImmersivePetroleum#243]
<details><summary><b>Crash Report:</b></summary>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AFMLLoadingPlugin (advmachinespatch-1.0.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  MicdoodlePlugin (Galacticraft-1.12.2-4.0.2.284.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.21.2_Forge_1.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
  AFMLLoadingPlugin (advsolarpatch-1.1.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_22.7.0_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 5/12/22 9:26 PM
XRay version: 58
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from BuildCraft Lib (buildcraftlib)
Caused by: java.lang.Error: Failed to create a page link for immersivepetroleum:schematic class flaxbeard.immersivepetroleum.common.items.ItemProjector ({id:"immersivepetroleum:schematic",Count:1b,tag:{multiblock:"II:Packer"},Damage:0s})
	at buildcraft.lib.client.guide.entry.PageEntryItemStack.iterateAllDefault(PageEntryItemStack.java:114)
	at buildcraft.lib.client.guide.GuideManager.generateContentsPage(GuideManager.java:337)
	at buildcraft.lib.client.guide.GuideManager.reload0(GuideManager.java:203)
	at buildcraft.lib.client.guide.GuideManager.reload(GuideManager.java:132)
	at buildcraft.lib.client.guide.GuideManager.func_110549_a(GuideManager.java:119)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121)
	at buildcraft.lib.BCLibProxy$ClientProxy.fmlPostInit(BCLibProxy.java:173)
	at buildcraft.lib.BCLib.postInit(BCLib.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
	at flaxbeard.immersivepetroleum.common.items.ItemProjector.func_77624_a(ItemProjector.java:92)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:707)
	at buildcraft.lib.misc.GuiUtil.getUnFormattedTooltip(GuiUtil.java:449)
	at buildcraft.lib.client.guide.parts.contents.PageLinkItemStack.getTooltip(PageLinkItemStack.java:43)
	at buildcraft.lib.client.guide.parts.contents.PageLinkItemStack.create(PageLinkItemStack.java:29)
	at buildcraft.lib.client.guide.entry.PageEntryItemStack.iterateAllDefault(PageEntryItemStack.java:110)
	... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1307924392 bytes (1247 MB) / 4294967296 bytes (4096 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -Xms4G -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 72 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version                  | Source                                          | Signature                                |
	|:----- |:--------------------- |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJ | minecraft             | 1.12.2                   | minecraft.jar                                   | None                                     |
	| LCHIJ | mcp                   | 9.42                     | minecraft.jar                                   | None                                     |
	| LCHIJ | FML                   | 8.0.99.99                | forge-1.12.2-14.23.5.2860.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge                 | 14.23.5.2860             | forge-1.12.2-14.23.5.2860.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | advmachinespatchcore  | 1.0                      | minecraft.jar                                   | None                                     |
	| LCHIJ | advsolarpatchcore     | 1.0                      | minecraft.jar                                   | None                                     |
	| LCHIJ | micdoodlecore         | 4.0.2.284                | minecraft.jar                                   | None                                     |
	| LCHIJ | xaerominimap_core     | 1.12.2-1.0               | minecraft.jar                                   | None                                     |
	| LCHIJ | xaeroworldmap_core    | 1.12.2-1.0               | minecraft.jar                                   | None                                     |
	| LCHIJ | ic2                   | 2.8.221-ex112            | industrialcraft-2-2.8.221-ex112.jar             | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJ | advanced_machines     | 61.0.1                   | Advanced Machines-61.0.1.jar                    | None                                     |
	| LCHIJ | advanced_solar_panels | 4.3.0                    | Advanced+Solar+Panels-4.3.0.jar                 | None                                     |
	| LCHIJ | advmachinespatch      | 1.0                      | advmachinespatch-1.0.jar                        | None                                     |
	| LCHIJ | advsolarpatch         | 1.1                      | advsolarpatch-1.1.jar                           | None                                     |
	| LCHIJ | appliedenergistics2   | rv6-stable-7             | appliedenergistics2_rv6_stable_7_1.12.2.jar     | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJ | baubles               | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| LCHIJ | mantle                | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                        | None                                     |
	| LCHIJ | jei                   | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                       | None                                     |
	| LCHIJ | tinkersextras         | 1.12.2-1.1.0             | TinkersExtras-1.12.2-1.1.0.jar                  | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHIJ | tconstruct            | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                | None                                     |
	| LCHIJ | p455w0rdslib          | 2.3.161                  | p455w0rdslib-1.12.2-2.3.161.jar                 | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJ | ae2wtlib              | 1.0.34                   | AE2WTLib-1.12.2-1.0.34.jar                      | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJ | appleskin             | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                     | None                                     |
	| LCHIJ | galacticraftcore      | 4.0.2.284                | Galacticraft-1.12.2-4.0.2.284.jar               | None                                     |
	| LCHIJ | galacticraftplanets   | 4.0.2.284                | Galacticraft-1.12.2-4.0.2.284.jar               | None                                     |
	| LCHIJ | asmodeuscore          | 0.0.30                   | AsmodeusCore-1.12.2-0.0.30.jar                  | None                                     |
	| LCHIJ | betteradvancements    | 0.1.0.77                 | BetterAdvancements-1.12.2-0.1.0.77.jar          | None                                     |
	| LCHIJ | betterbuilderswands   | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar | None                                     |
	| LCHIJ | bookshelf             | 2.3.590                  | Bookshelf-1.12.2-2.3.590.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJ | botania               | r1.10-364                | Botania r1.10-364.4.jar                         | None                                     |
	| LCHIE | buildcraftlib         | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcraftcore        | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcraftbuilders    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcrafttransport   | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcraftsilicon     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcraftcompat      | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcraftenergy      | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcraftfactory     | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | buildcraftrobotics    | 7.99.24.8                | buildcraft-all-7.99.24.8.jar                    | None                                     |
	| LCHI  | cctweaked             | 1.83.0                   | cc-tweaked-1.12.2-1.83.0.jar                    | None                                     |
	| LCHI  | computercraft         | 1.83.0                   | cc-tweaked-1.12.2-1.83.0.jar                    | None                                     |
	| LCHI  | chameleon             | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| LCHI  | codechickenlib        | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHI  | elevatorid            | 1.3.14                   | ElevatorMod-1.12.2-1.3.14.jar                   | None                                     |
	| LCHI  | epicsiegemod          | 13.167                   | EpicSiegeMod-13.167.jar                         | None                                     |
	| LCHI  | waila                 | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                     | None                                     |
	| LCHI  | extracells            | 2.6.5                    | ExtraCells-1.12.2-2.6.5.jar                     | None                                     |
	| LCHI  | mjrlegendslib         | 1.12.2-1.2.1             | MJRLegendsLib-1.12.2-1.2.1.jar                  | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHI  | extraplanets          | 1.12.2-0.7.4             | ExtraPlanets-1.12.2-0.7.4.jar                   | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LCHI  | gravisuite            | 3.1.1                    | Gravitation Suite-3.1.1.jar                     | None                                     |
	| LCHI  | immersiveengineering  | 0.12-98                  | ImmersiveEngineering-0.12-98.jar                | None                                     |
	| LCHI  | immersive_energy      | 0.5.5                    | Immersive Energy-1.12.2-0.5.5.jar               | None                                     |
	| LCHI  | immersivecables       | 1.3.2                    | ImmersiveCables-1.12.2-1.3.2.jar                | None                                     |
	| LCHI  | immersivepetroleum    | 1.1.10                   | immersivepetroleum-1.12.2-1.1.10.jar            | None                                     |
	| LCHI  | inventorytweaks       | 1.64+dev.146.2180b27     | InventoryTweaks-1.64+dev.146.jar                | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCHI  | immersivetech         | 1.9.100                  | MCTImmersiveTechnology-1.12.2-1.9.100.jar       | None                                     |
	| LCHI  | mm_lib                | 2.3.0                    | MMLib-2.3.0.jar                                 | None                                     |
	| LCHI  | patchouli             | 1.0-23.6                 | Patchouli-1.0-23.6.jar                          | None                                     |
	| LCHI  | plustic               | 8.0.0.1                  | plustic-8.0.0.1.jar                             | None                                     |
	| LCHI  | reactor_stuff         | 1.10.2                   | ReactorStuff-[1.12.2]-1.10.2.jar                | None                                     |
	| LCHI  | simpleplanes          | 3.0.1.7                  | simpleplanes-1.12.2-3.0.1.7.jar                 | None                                     |
	| LCHI  | flammpfeil.slashblade | mc1.12-r33               | SlashBlade-mc1.12-r33.jar                       | None                                     |
	| LCHI  | slashbladetic         | 1.5.0-MC1.12.2           | SlashBladeTic-1.5.0-MC1.12.2.jar                | None                                     |
	| LCHI  | storagedrawers        | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                 | None                                     |
	| LCHI  | tinkertoolleveling    | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar             | None                                     |
	| LCHI  | veinminer             | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |
	| LCHI  | veinminermodsupport   | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |
	| LCHI  | wailaharvestability   | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar           | None                                     |
	| LCHI  | wct                   | 3.12.97                  | WirelessCraftingTerminal-1.12.2-3.12.97.jar     | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHI  | xaerominimap          | 22.7.0                   | Xaeros_Minimap_22.7.0_Forge_1.12.jar            | None                                     |
	| LCHI  | xaeroworldmap         | 1.21.2                   | XaerosWorldMap_1.21.2_Forge_1.12.jar            | None                                     |
	| LCHI  | immersiveintelligence | 0.2.1                    | immersiveintelligence-0.2.1.jar                 | 770570c49a2652e64a9b29b9b9d9919ca68b7065 |

	Loaded coremods (and transformers): 
AFMLLoadingPlugin (advmachinespatch-1.0.jar)
  mods.su5ed.advmachinespatch.asm.AClassTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
MicdoodlePlugin (Galacticraft-1.12.2-4.0.2.284.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
XaeroWorldMapPlugin (XaerosWorldMap_1.21.2_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
  xaero.map.core.transformer.WorldClientTransformer
  xaero.map.core.transformer.PlayerListTransformer
  xaero.map.core.transformer.SaveFormatTransformer
  xaero.map.core.transformer.BiomeColorHelperTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.64+dev.146.jar)
  invtweaks.forge.asm.ContainerTransformer
IILoadingPlugin (immersiveintelligence-core-0.2.1.jar)
  pl.pabilo8.immersiveintelligence.common.asm.IIClassTransformer
AFMLLoadingPlugin (advsolarpatch-1.1.jar)
  mods.su5ed.advsolarpatch.asm.AClassTransformer
XaeroMinimapPlugin (Xaeros_Minimap_22.7.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.SaveFormatTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
	GL info: ' Vendor: 'Apple' Version: '2.1 Metal - 76.3' Renderer: 'Apple M1 Pro'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	Patchouli open book context: n/a
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:ON, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
</details>

**Comment by Phaeton20** [comment]
https://github.com/BuildCraft/BuildCraft/issues/4664 Is a kind of temporary fix
