### ISSUE TITLE
Crash-Report 1.12 (immersivepetroleum-1.12-1.0.7)

### ISSUE THREAD

**Issue by cyberpunkbln** [Flaxbeard/ImmersivePetroleum#39]
Hello,
fresh downloaded:).
here are the crash-report:

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (movingworld-1.12-2.337-full.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  HammerCoreCore (HammerCore_1.12-1.9.2.jar)
  ForgelinPlugin (Forgelin-1.5.0.jar)
  BCModPlugin (zz-backpacks 1.12 - 3.1.9.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.5.7.jar)
Contact their authors BEFORE contacting forge

// On the bright side, I bought you a teddy bear!

Time: 7/14/17 12:45 AM
Description: Initializing game

com.google.gson.JsonSyntaxException: Could not find IIngredientFactory: blusunrize.immersiveengineering.common.crafting.IngredientFactoryFluidStack
	at net.minecraftforge.common.crafting.CraftingHelper.getClassInstance(CraftingHelper.java:591)
	at net.minecraftforge.common.crafting.CraftingHelper.loadFactories(CraftingHelper.java:555)
	at net.minecraftforge.common.crafting.CraftingHelper.loadFactories(CraftingHelper.java:641)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:613)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:779)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:343)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.common.crafting.IngredientFactoryFluidStack
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.common.crafting.CraftingHelper.getClassInstance(CraftingHelper.java:584)
	... 15 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.common.crafting.CraftingHelper.getClassInstance(CraftingHelper.java:591)
	at net.minecraftforge.common.crafting.CraftingHelper.loadFactories(CraftingHelper.java:555)
	at net.minecraftforge.common.crafting.CraftingHelper.loadFactories(CraftingHelper.java:641)
	at java.util.ArrayList.forEach(Unknown Source)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:613)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:779)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:343)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_101, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1167785160 bytes (1113 MB) / 2685038592 bytes (2560 MB) up to 8576565248 bytes (8179 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn128M -Xms128M -Xmx8G -XX:MetaspaceSize=128M -XX:MaxMetaspaceSize=512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2410 Optifine OptiFine_1.12_HD_U_C4 78 mods loaded, 78 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2410.jar) 
	UCH	forge{14.21.1.2410} [Minecraft Forge] (forge-1.12-14.21.1.2410.jar) 
	UCH	aroma1997core{1.3.0.0.b94} [Aroma1997Core] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCH	backpacks16840{3.1.9} [Backpacks!] (zz-backpacks 1.12 - 3.1.9.jar) 
	UCH	com.elytradev.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCH	actuallyadditions{1.12-r114} [Actually Additions] (ActuallyAdditions-1.12-r114.jar) 
	UCH	jei{4.7.1.69} [Just Enough Items] (jei_1.12-4.7.1.69.jar) 
	UCH	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.12-1.0.7.jar) 
	UCH	aroma1997corehelper{1.3.0.0.b94} [Aroma1997Core|Helper] (Aroma1997Core-1.12-1.3.0.0.b94.jar) 
	UCH	aroma1997sdimension{1.3.0.0.b37} [Aroma1997's Dimensional World] (Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar) 
	UCH	bibliocraft{2.4.2} [BiblioCraft] (BiblioCraft[v2.4.2][MC1.12.0].jar) 
	UCH	biomesoplenty{7.0.0.2289} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2289-universal.jar) 
	UCH	chameleon{1.12-4.1.1} [Chameleon] (Chameleon-1.12-4.1.1.jar) 
	UCH	chisel{MC1.12-0.0.13.12} [Chisel] (Chisel-MC1.12-0.0.13.12.jar) 
	UCH	clayworldgen{1.1.0-1.12} [Clay WorldGen] (ClayWorldGen-1.1.0-1.12.0.jar) 
	UCH	codechickenlib{3.1.0.278} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.0.278-universal.jar) 
	UCH	redstoneflux{2.0.1} [Redstone Flux] (RedstoneFlux-1.12-2.0.1.2-universal.jar) 
	UCH	cofhcore{4.3.2} [CoFH Core] (CoFHCore-1.12-4.3.2.7-universal.jar) 
	UCH	cofhworld{1.0.0} [CoFH World] (CoFHWorld-1.12-1.0.0.6-universal.jar) 
	UCH	ctm{MC1.12-0.2.0.3} [CTM] (CTM-MC1.12-0.2.0.3.jar) 
	UCH	dailies{1.12-6} [Bailey's Dailies] (dailies-1.12-6.jar) 
	UCH	movingworld{1.12-2.337} [Moving World] (movingworld-1.12-2.337-full.jar) 
	UCH	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.12-2.331-full.jar) 
	UCH	dsurround{3.4.5.7} [Dynamic Surroundings] (DynamicSurroundings-1.12-3.4.5.7.jar) 
	UCH	presets{3.4.5.7} [Presets!] (DynamicSurroundings-1.12-3.4.5.7.jar) 
	UCH	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UCH	shetiphiancore{3.5.0.1} [ShetiPhian-Core] (shetiphiancore-1.12.0-3.5.0.1.jar) 
	UCH	endertanks{1.6.0.1} [EnderTanks] (endertanks-1.12.0-1.6.0.1.jar) 
	UCH	extrautils2{1.0} [extrautils2] (extrautils2-1.12-1.5.jar) 
	UCH	zerocore{1.12-0.1.0.9} [Zero CORE] (zerocore-1.12-0.1.0.9.jar) 
	UCH	bigreactors{1.12-0.4.5.33} [Extreme Reactors] (ExtremeReactors-1.12-0.4.5.33.jar) 
	UCH	forestry{5.4.3.131} [Forestry] (forestry_1.12-5.4.3.131.jar) 
	UCH	forgelin{1.4.2} [Shadowfacts' Forgelin] (Forgelin-1.5.0.jar) 
	UCH	fp{26.1.1} [Futurepack] (Futurepack-1.12-26.1.1.jar) 
	UCH	fp.api{1.1.0} [Futurepack API] (Futurepack-1.12-26.1.1.jar) 
	UCH	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UCH	hammercore{1.9.2} [Hammer Core] (HammerCore_1.12-1.9.2.jar) 
	UCH	hardcoreore{0.0.2} [Hardcore ORE] (hardcoreore-1.12-0.0.2.jar) 
	UCH	tesla{1.0.60} [TESLA] (Tesla-1.12-1.0.60.jar) 
	UCH	theoneprobe{1.4.11} [The One Probe] (theoneprobe-1.12-1.4.11.jar) 
	UCH	immersiveengineering{0.12-64} [Immersive Engineering] (ImmersiveEngineering-0.12-64.jar) 
	UCH	immersivepetroleum{1.0.7} [Immersive Petroleum] (immersivepetroleum-1.12-1.0.7.jar) 
	UCH	improvedbackpacks{1.12-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.12-1.1.2.0.jar) 
	UCH	improvedextraction{0.1.2-BETA} [Improved Extraction] (ImprovedExtraction-1.12-0.1.2-BETA.jar) 
	UCH	teslacorelib{@@VERSION@@} [Tesla Core Lib] (tesla-core-lib-1.12-1.0.3.jar) 
	UCH	industrialforegoing{1.11.2-1.0-BETA} [Industrial Foregoing] (industrialforegoing-1.12-1.0-BETA-16.jar) 
	UCH	infinitefluids{1.1.1} [InfiniteFluids] (infinitefluids-1.11-1.1.1.jar) 
	UCH	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UCH	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UCH	modnametooltip{1.8.1} [Mod Name Tooltip] (modnametooltip_1.12-1.8.1.jar) 
	UCH	moreoverlays{1.12} [MoreOverlays] (moreoverlays-1.12-mc1.12.jar) 
	UCH	multibeds{1.4.0.1} [Multi-Beds] (multibeds-1.12.0-1.4.0.1.jar) 
	UCH	multistorage{1.4.0.1} [Multi-Storage] (multistorage-1.12.0-1.4.0.1.jar) 
	UCH	platforms{1.4.0.1} [Platforms] (platforms-1.12.0-1.4.0.1.jar) 
	UCH	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UCH	rangedpumps{0.5} [Ranged Pumps] (rangedpumps-0.5.jar) 
	UCH	thermalfoundation{2.3.2} [Thermal Foundation] (ThermalFoundation-1.12-2.3.2.8-universal.jar) 
	UCH	thermalexpansion{5.3.2} [Thermal Expansion] (ThermalExpansion-1.12-5.3.2.10-universal.jar) 
	UCH	redstonearsenal{2.3.2} [Redstone Arsenal] (RedstoneArsenal-1.12-2.3.2.6-universal.jar) 
	UCH	storagedrawers{1.12-5.2.5} [Storage Drawers] (StorageDrawers-1.12-5.2.7.jar) 
	UCH	refinedstorage{1.5.8} [Refined Storage] (refinedstorage-1.5.8.jar) 
	UCH	rftools{6.10} [RFTools] (rftools-1.12-6.10beta4.jar) 
	UCH	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.12-1.6.8beta1.jar) 
	UCH	rftoolsdim{5.02} [RFTools Dimensions] (rftoolsdim-1.12-5.02beta3.jar) 
	UCH	silentlib{2.2.6} [Silent Lib] (SilentLib-1.12-2.2.6-83.jar) 
	UCH	silentgems{2.4.2} [Silent's Gems] (SilentsGems-1.12-2.4.2-206.jar) 
	UCH	sgextraparts{1.3.1} [Silent's Gems: Extra Parts] (SGExtraParts-1.12-1.3.1-25.jar) 
	UCH	simplequarry{1.0.5} [Simple Quarry] (Simple Quarry 1.12-1.0.5.jar) 
	UCH	soundfilters{0.10_for_1.12} [Sound Filters] (SoundFilters-0.10_for_1.12.jar) 
	UCH	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.12-3.1.0.jar) 
	UCH	thermalcultivation{0.1.0} [Thermal Cultivation] (ThermalCultivation-1.12-0.1.0.5-universal.jar) 
	UCH	thermaldynamics{2.3.2} [Thermal Dynamics] (ThermalDynamics-1.12-2.3.2.9-universal.jar) 
	UCH	toolbelt{1.6.4} [Tool Belt] (ToolBelt-1.12.0-1.6.4.jar) 
	UCH	torohealthmod{1.12-11} [ToroHealth Damage Indicators] (torohealth-1.12-11.jar) 
	UCH	treechopper{1.2.1} [Tree Chopper] (TreeChopper-1.12-1.2.1.jar) 
	UCH	teslacoreregistries{@@VERSION@@} [Tesla Core Registries] (tesla-core-lib-1.12-1.0.3.jar) 
	Loaded coremods (and transformers): 
MovingWorldCoreMod (movingworld-1.12-2.337-full.jar)
  
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.0.1.jar)
  shetiphian.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12-0.2.0.3.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoreMod (Aroma1997Core-1.12-1.3.0.0.b94.jar)
  
HammerCoreCore (HammerCore_1.12-1.9.2.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
ForgelinPlugin (Forgelin-1.5.0.jar)
  
BCModPlugin (zz-backpacks 1.12 - 3.1.9.jar)
  brad16840.common.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.5.7.jar)
  org.blockartistry.DynSurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.05' Renderer: 'GeForce GTX 950M/PCIe/SSE2'
	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	Launched Version: 1.12-forge1.12-14.21.1.2410
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 950M/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.05, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: MakeRPs.zip (incompatible), Clouds-Pack (Modified) - updated.zip (incompatible)
	Current Language: Deutsch (Deutschland)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.12_HD_U_C4
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 382.05
	OpenGlRenderer: GeForce GTX 950M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8`

**Comment by cyberpunkbln** [comment]
Upps i must use ImmersiveEngineering-0.12-66
