### ISSUE TITLE
Exception loading model for variant

### ISSUE THREAD

**Issue by trilexcom** [Flaxbeard/ImmersivePetroleum#81]
hi Immersive Petroleum / Flaxbeard 

we are getting a error from console error is below 

Exception loading model for variant immersivepetroleum:metal_multiblock#_0multiblockslave=true,_1dynamicrender=true,boolean0=false,facing=north,type=pumpjack_parent net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model immersivepetroleum:metal_multiblock#_0multiblockslave=true,_1dynamicrender=true,boolean0=false,facing=north,type=pumpjack_parent with loader VariantLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:233) 	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:153) 	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:221) 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:48) 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model minecraft:block/cube-all with loader VanillaLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.<init>(ModelLoader.java:660) 	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1170) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 15 more Caused by: java.io.FileNotFoundException: minecraft:models/block/cube-all.json 	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) 	at net.minecraft.client.renderer.block.model.ModelBakery.func_177594_c(ModelBakery.java:334) 	at net.minecraftforge.client.model.ModelLoader.access$1600(ModelLoader.java:126) 	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:860) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 18 more
--
17:44:12 | FML | main | error | Exception loading model for variant immersivepetroleum:metal_multiblock#_0multiblockslave=true,_1dynamicrender=true,boolean0=false,facing=south,type=pumpjack net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model immersivepetroleum:metal_multiblock#_0multiblockslave=true,_1dynamicrender=true,boolean0=false,facing=south,type=pumpjack with loader VariantLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader.func_177569_a(ModelLoader.java:233) 	at net.minecraft.client.renderer.block.model.ModelBakery.loadBlock(ModelBakery.java:153) 	at net.minecraftforge.client.model.ModelLoader.func_188640_b(ModelLoader.java:221) 	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:48) 	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SimpleReloadableResourceManager.java:121) 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:512) 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) 	at net.minecraft.client.main.Main.main(SourceFile:123) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: net.minecraftforge.client.model.ModelLoaderRegistry$LoaderException: Exception loading model minecraft:block/cube-all with loader VanillaLoader.INSTANCE, skipping 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:153) 	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.<init>(ModelLoader.java:660) 	at net.minecraftforge.client.model.ModelLoader$VariantLoader.loadModel(ModelLoader.java:1170) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 15 more Caused by: java.io.FileNotFoundException: minecraft:models/block/cube-all.json 	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:69) 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) 	at net.minecraft.client.renderer.block.model.ModelBakery.func_177594_c(ModelBakery.java:334) 	at net.minecraftforge.client.model.ModelLoader.access$1600(ModelLoader.java:126) 	at net.minecraftforge.client.model.ModelLoader$VanillaLoader.loadModel(ModelLoader.java:860) 	at net.minecraftforge.client.model.ModelLoaderRegistry.getModel(ModelLoaderRegistry.java:149) 	... 18 more

MC : 1.12.2
Forge : 2556
Crashlog : https://pastebin.com/NWMF4wvg
Immersive Eng : immersiveengeering-0-12-75
Immserive Pet : immersivepetroleum-1.12-2-1.1.5

Thanks 

Mat

**Comment by DoomRater** [comment]
I should note that there is no model that shows up in WAILA when I look at the distiller or pumpjack, but there is one for Immersive Engineering models like the Excavator and Crusher.  I get a missing texture-ish block when I look at them.

I am on 1.1.9.
